### PR TITLE
Unit test for exec_composer - Closes #96

### LINKED ISSUE #96: Unit tests remaining functionalities of Circuit
## Description

Cover following scenarios with unit tests

### Contracts registry [Beqa]

- [ ] purge fails (contract missing + non-root user case)
- [ ] add_new_contract fails (contract already exists + non-root user case)

### Execution delivery
- [x] register gateway fail and success; 4 different tests for each header and block size combination  [Maciej]
- [ ] submit_step_confirmation fail and success; 4 different tests for each header and block size combination [Maciej]
- [ ] dry_run_single_contract; other success paths, other failure paths [Devanshu]
- [ ] preload_bunch_of_contracts [Devanshu]
- [ ] run_single_contract [Devanshu]
- [ ] pre_run_bunch_until_break; depends on above two functions [Devanshu]
- [ ] retrieve_gateway_pointer [Beqa]
- [ ] retrieve_gateway_protocol [Beqa]
- [ ] dry_run_whole_xtx [Beqa]

### PR DESCRIPTION
**Pull request by devanshu0987**
Added unit tests for exec_composer.
Multiple cases for : run_single_contract , preload_bunch_of_contracts
Rearranged the order.

### CODE REVIEW

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 1]
```diff
@@ -849,4 +892,303 @@ mod tests {
...
+            insert_default_xdns_record();
+            let res = ExecComposer::preload_bunch_of_contracts::<Test>(
+                vec![temp_contract_one],
+                Default::default(),
+            );
+
+            assert_ok!(res);
+            // If we are able to unwrap, it means the contract was inserted.
+            let _fetched_contract =
+                volatile_vm::Pallet::<Test>::get_contract_code_lazy(executable.code_hash).unwrap();
```
Comment (zannis) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:970]: You can replace this one with an assert! macro.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 2]
```diff
@@ -849,4 +892,303 @@ mod tests {
...
+
+        let compose_one =
+            make_compose_out_of_raw_wat_code::<Test>(CODE_CALL, vec![], requester.clone(), value);
+
+        let compose_two = make_compose_out_of_raw_wat_code::<Test>(
+            WROONG_CODE_MODULE_DISPATCH_NO_FUNC,
+            vec![],
+            requester.clone(),
+            value,
+        );
```
Comment (zannis) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:912]: Hmm somehow I think this should break for a contract with wrong wasm code?

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 3]
```diff
@@ -548,6 +591,50 @@ mod tests {
 
 	(data (i32.const 44) "\01\02\03\04")
 )
+"#;
+
+    const WROONG_CODE_MODULE_DISPATCH_NO_FUNC: &str = r#"
```
Comment (zannis) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:596]: Typo here in the word WRONG.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 4]
```diff
@@ -849,4 +892,303 @@ mod tests {
...
+                Default::default(),
+                Default::default(),
+            );
+
+            assert_eq!(res, Err("Can't decode WASM code"));
+        });
+    }
+
+    #[test]
+    #[ignore = "Please implement proper assertions when retrieve_gateway_protocol is properly implemented"]
```
Comment (zannis) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:1135]: Yeah this needs #87 to be merged first.

**Review by zannis — CHANGES_REQUESTED** [review]
Overall this PR is looking fine, some minor changes requested and please also extract the tests to their own file 'tests.rs' under the same directory and add it as a module to the library.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 5]
```diff
@@ -849,4 +892,303 @@ mod tests {
...
+
+        ext.execute_with(|| {
+            insert_default_xdns_record();
+
+            let res = ExecComposer::preload_bunch_of_contracts::<Test>(
+                vec![temp_contract_one],
+                Default::default(),
+            );
+
+            assert_eq!(res, Err("Can't decode WASM code"));
```
Comment (beqaabu) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:1017]: You can use assert_err! macro when asserting errors

**Review by beqaabu — COMMENTED** [review]
The PR looks good!

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 2 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs:912]: There is another variable called INVALID_CODE. That is wrong wasm code.
This one compiles fine. As per the name suggests, it would fail when it runs. Will find out more.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 5 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs:1017]: `#[macro_export]
macro_rules! assert_err {
	( $x:expr , $y:expr $(,)? ) => {
		assert_eq!($x, Err($y.into()));
	}
}`

The macro does the same thing. But makes sense, it is always good to be explicit in what we want.
Replaced all the places where Error was being asserted.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 2 above)
Comment (zannis) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: Sounds good!

Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: I went through the substrate repo and searched for this particular contract. It is not there. Most probably they have changed it over time.
At this point, I am not sure what this wat does, except that it compiles.

File: circuit/src/contracts-registry/src/tests.rs [hunk 6]
```diff
@@ -336,3 +337,238 @@ fn fetch_contracts_with_no_parameters_should_error() {
         assert_err!(actual, Error::UnknownContract);
     })
 }
+
+#[test]
+fn add_new_contract_success() {
```
Comment (MaciejBaj) [inline circuit/src/contracts-registry/src/tests.rs:342]:
```suggestion
fn add_new_contract_succeeds_for_default() {
```

File: circuit/src/contracts-registry/src/tests.rs [hunk 7]
```diff
@@ -336,3 +337,238 @@ fn fetch_contracts_with_no_parameters_should_error() {
...
+            assert_ok!(ContractsRegistry::add_new_contract(
+                origin,
+                requester,
+                test_contract.clone()
+            ));
+        })
+}
+
+#[test]
+fn add_new_contract_fails_if_origin_not_root() {
```
Comment (MaciejBaj) [inline circuit/src/contracts-registry/src/tests.rs:380]:
```suggestion
fn add_new_contract_fails_for_no_sudo_origin() {
```

File: circuit/src/contracts-registry/src/tests.rs [hunk 8]
```diff
@@ -336,3 +337,238 @@ fn fetch_contracts_with_no_parameters_should_error() {
...
+        );
+        assert_err!(
+            ContractsRegistry::add_new_contract(origin, requester, test_contract.clone()),
+            Error::<Test>::ContractAlreadyExists
+        )
+    })
+}
+
+#[test]
+fn purge_success() {
```
Comment (MaciejBaj) [inline circuit/src/contracts-registry/src/tests.rs:455]:
```suggestion
fn purge_succeeds_for_default_contract() {
```

File: circuit/src/contracts-registry/src/tests.rs [hunk 9]
```diff
@@ -336,3 +337,238 @@ fn fetch_contracts_with_no_parameters_should_error() {
...
+
+    ExtBuilder::default()
+        .with_contracts(vec![test_contract.clone()])
+        .build()
+        .execute_with(|| {
+            crate::ContractsRegistry::<Test>::insert(
+                test_contract.generate_id::<Test>(),
+                test_contract.clone(),
+            );
+            assert_ok!(ContractsRegistry::purge(origin, requester, contract_id));
```
Comment (MaciejBaj) [inline circuit/src/contracts-registry/src/tests.rs:490]: Check here that `ContractsRegistry::get(contract_id)` returns none

File: circuit/src/contracts-registry/src/tests.rs [hunk 10]
```diff
@@ -336,3 +337,238 @@ fn fetch_contracts_with_no_parameters_should_error() {
...
+            crate::ContractsRegistry::<Test>::insert(
+                test_contract.generate_id::<Test>(),
+                test_contract.clone(),
+            );
+            assert_err!(
+                ContractsRegistry::purge(origin, requester, contract_id),
+                DispatchError::BadOrigin
+            );
+        })
+}
```
Comment (MaciejBaj) [inline circuit/src/contracts-registry/src/tests.rs:574]: Add missing space

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 11]
```diff
@@ -504,6 +516,37 @@ mod tests {
         hex_literal::hex!["d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d"].into()
     }
 
+    fn make_registry_contract_out_of_wat<T: Config>(
```
Comment (MaciejBaj) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:519]: Possible to re-use that function from other files where  both `make_compose_out_of_raw_wat_code` + `RegistryContract::from_compose` are used? pretty sure it's the case this logic has been implemented in some other tests too

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 12]
```diff
@@ -849,4 +892,335 @@ mod tests {
             )
         });
     }
+
+    #[test]
+    fn pre_run_bunch_until_break_multiple_contracts_succeeds() {
```
Comment (MaciejBaj) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:897]:
```suggestion
    fn pre_run_bunch_until_break_succeds_for_both_contracts() {
```

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 13]
```diff
@@ -849,4 +892,335 @@ mod tests {
...
+                vec![temp_contract_one, temp_contract_two],
+                Default::default(),
+            );
+
+            assert_ok!(res);
+        });
+    }
+
+    #[test]
+    fn preload_bunch_of_contracts_one_contract_fails() {
```
Comment (MaciejBaj) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:999]: Unclear name

File: circuit/src/execution-delivery/src/exec_composer/mod.rs [hunk 14]
```diff
@@ -849,4 +892,335 @@ mod tests {
...
+                vec![temp_contract_one, temp_contract_two],
+                Default::default(),
+            );
+
+            assert_err!(res, "Can't decode WASM code");
+        });
+    }
+
+    #[test]
+    fn run_single_contract_fails_stack_error() {
```
Comment (MaciejBaj) [inline circuit/src/execution-delivery/src/exec_composer/mod.rs:1050]: Change naming to say when fails with stack error. Repeat in following test names too

**Review by MaciejBaj — CHANGES_REQUESTED** [review]

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 4 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: I will let this test stay.
And I have refactored the tests out into a new file.
I am resolving this comment.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 14 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: Hi @MaciejBaj , I have tried to improve the test names. Please take a look.
I have used this scheme : functionName_result_stateInfo wherever applicable.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 12 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: pre_run_bunch_until_break_succeeds_for_two_contracts

I have used this. It feels important to say that only 2 contracts are being tested.
Resolving this.

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 13 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: Improved. Please check tests.rs

File: circuit/src/execution-delivery/src/exec_composer/mod.rs (hunk 11 above)
Comment (devanshu0987) [reply circuit/src/execution-delivery/src/exec_composer/mod.rs]: As per offline discussion, resolving this comment.

**Review by MaciejBaj — APPROVED** [review]

File: circuit/src/contracts-registry/src/tests.rs (hunk 6 above)
Comment (beqaabu) [reply circuit/src/contracts-registry/src/tests.rs]: Fix on the latest commit

File: circuit/src/contracts-registry/src/tests.rs (hunk 7 above)
Comment (beqaabu) [reply circuit/src/contracts-registry/src/tests.rs]: Fixed on the latest commit

File: circuit/src/contracts-registry/src/tests.rs (hunk 8 above)
Comment (beqaabu) [reply circuit/src/contracts-registry/src/tests.rs]: Fixed on the latest commit

File: circuit/src/contracts-registry/src/tests.rs (hunk 9 above)
Comment (beqaabu) [reply circuit/src/contracts-registry/src/tests.rs]: Fixed on the latest commit

File: circuit/src/contracts-registry/src/tests.rs (hunk 10 above)
Comment (beqaabu) [reply circuit/src/contracts-registry/src/tests.rs]: Fixed on the latest commit

**Review by zannis — APPROVED** [review]
Looking good!
